export const items = {
    ladyJeans : [
        { url : './images/lj1.jpg', type: 'trouser' },
        { url : './images/lj2.jpg', type: 'trouser' },
        { url : './images/lj3.jpg', type: 'trouser' },
        { url : './images/lj4.jpg', type: 'trouser' },
        { url : './images/lj5.jpg', type: 'trouser' },
        { url : './images/lj6.jpg', type: 'trouser' },
        { url : './images/lj7.jpg', type: 'trouser' },
    ],
    varsity : [
        { url : './images/v1.jpg', type: 'jacket' },
        { url : './images/v2.jpg', type: 'jacket' },
        { url : './images/v3.jpg', type: 'jacket' },
        { url : './images/v4.jpg', type: 'jacket' },
        { url : './images/v5.jpg', type: 'jacket' },
        { url : './images/v6.jpg', type: 'jacket' },
        { url : './images/v7.jpg', type: 'jacket' },
    ],
    puffer : [
        { url : './images/pf1.jpg', type: 'jacket' },
        { url : './images/pf2.jpg', type: 'jacket' },
        { url : './images/pf3.jpg', type: 'jacket' },
        { url : './images/pf4.jpg', type: 'jacket' },
        { url : './images/pf5.jpg', type: 'jacket' },
    ],
    fleece : [
        { url : './images/fl1.jpg', type: 'jacket' },
        { url : './images/fl2.jpg', type: 'jacket' },
        { url : './images/fl3.jpg', type: 'jacket' },
        { url : './images/fl4.jpg', type: 'jacket' },
        { url : './images/fl5.jpg', type: 'jacket' },
    ],
    maleJeans : [
        { url : './images/mj1.jpg', type: 'trouser' },
        { url : './images/mj2.jpg', type: 'trouser' },
        { url : './images/mj3.jpg', type: 'trouser' },
        { url : './images/mj4.jpg', type: 'trouser' },
        { url : './images/mj5.jpg', type: 'trouser' },
        { url : './images/mj6.jpg', type: 'trouser' },
        { url : './images/mj7.jpg', type: 'trouser' },
    ],
    momJeans : [
        { url : './images/mom1.jpg', type: 'trouser' },
        { url : './images/mom2.jpg', type: 'trouser' },
        { url : './images/mom3.jpg', type: 'trouser' },
        { url : './images/mom4.jpg', type: 'trouser' },
        { url : './images/mom5.jpg', type: 'trouser' },
        { url : './images/mom6.jpg', type: 'trouser' },
    ],
    skirts : [
        { url : './images/sk1.jpg', type: 'skirt' },
        { url : './images/sk2.jpg', type: 'skirt' },
        { url : './images/sk3.jpg', type: 'skirt' },
        { url : './images/sk4.jpg', type: 'skirt' },
        { url : './images/sk5.jpg', type: 'skirt' },
    ],
    shirts : [
        { url : './images/fnl1.jpg', type: 'Flannel' },
        { url : './images/fnl2.jpg', type: 'Flannel' },
        { url : './images/fnl3.jpg', type: 'Flannel' },
        { url : './images/fnl4.jpg', type: 'Flannel' },
        { url : './images/fnl5.jpg', type: 'Flannel' },
        { url : './images/fnl6.jpg', type: 'Flannel' },
        { url : './images/fnl7.jpg', type: 'Flannel' },
    ]
}